"""recreate paradas table

Revision ID: 1a8a0c3346a1
Revises: a9b25ca6b72c
Create Date: 2026-09-12 16:11:14.835077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8a0c3346a1'
down_revision: Union[str, Sequence[str], None] = 'a9b25ca6b72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paradas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calle_principal', sa.String(length=100), nullable=False),
    sa.Column('esquina', sa.String(length=100), nullable=False),
    sa.Column('latitud', sa.Float(), nullable=False),
    sa.Column('longitud', sa.Float(), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paradas')
    # ### end Alembic commands ###
