"""Tabla paradas_omnibus creada

Revision ID: 572a1f51b16c
Revises: 1a8a0c3346a1
Create Date: 2026-09-13 20:10:23.737828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572a1f51b16c'
down_revision: Union[str, Sequence[str], None] = '1a8a0c3346a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paradas_omnibus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_parada', sa.Integer(), nullable=False),
    sa.Column('omnibus', sa.String(length=100), nullable=False),
    sa.Column('consultas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_update', sa.String(length=50), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_parada'], ['paradas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paradas_omnibus')
    # ### end Alembic commands ###
