"""EXP y Niveles agregados

Revision ID: a9b25ca6b72c
Revises: 5faaae5d2151
Create Date: 2026-09-12 15:57:47.947200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b25ca6b72c'
down_revision: Union[str, Sequence[str], None] = '5faaae5d2151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('users', sa.Column('exp', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exp')
    op.drop_column('users', 'level')
    # ### end Alembic commands ###
